### ISSUE TITLE
some bugs ??

### ISSUE THREAD

**Issue by anhuipl2010** [tominute/MKCFup#2]
complexMat.cpp line 17,35,50 if (fea == 0 & channel == 1)c = 1;   ----> "&" need changed to "&&"

**Comment by tominute** [comment]
“&” has the same effect as "&&" here because only 0 or 1 is used.

**Comment by anhuipl2010** [comment]
I test this alg on the data 'UAV123' drone air-to-ground view, I found the tracking performance is poor. I changed some params but not used.

**Comment by tominute** [comment]
We haven't tried this dataset. I guess our tracker is not suitable for UAV123 since it performs well on small-move datasets such as OTB2013 and NfS while it could only get the same accuracy as SRDCF on OTB100 which contains much more large-move videos. Thank you for your question.
