### ISSUE TITLE
begin the code

### ISSUE THREAD

**Issue by cploveflower** [tominute/MKCFup#7]
Hello@tominute:
          I have compile the code,and when I want to run the runMCKFup.cpp,
          it shows that cann't read the res file and the gt file,I don't know where is the file,
          the gt file is the groundtruth_rect.txt?can you tell me about it?Thank you!

**Comment by tominute** [comment]
The gt file is the groundtruth_rect.txt which is the same as that of OTB and you shall make sure the path is right. The res file is created by the code which stores the results. Good luck:)

**Comment by cploveflower** [comment]
I put the data file in ./sequences ,and I don't know whether I need to change the 
                     groundtruth_rect.txt into filename_gt.txt ,so I try to change the name,but I still make 
                    a failure.it still show the error as above.In this project,I just add the sequences file and 
                     its subfile, the subfile include the img file and the groundtruth_rect.txt ,can you help me 
                      to solve this problem,Thank you very much

**Comment by tominute** [comment]
All you need to do is to correct the code about the gt path e.g. sprintf(buf, "yourpath/MKCFup/sequences/%s/%s_gt.txt", name, name);

**Comment by cploveflower** [comment]
I have change it like this:
sprintf(buf, "E:/VS2013_OPENCV/face_tracker/sequences/%s/%s_gt.txt", name, name);
but it has no change

**Comment by cploveflower** [comment]
the above error has been solved,but another error is coming,
the code about sprintf(buf, "sequences/%s/%s_frames.txt", name, name),
what is the %s_frames.txt, I can't find the file about %s_frame.txt in the OTB dataset

**Comment by tominute** [comment]
Oh, that includes the number of start_frame and end_frame. e.g. 1,100. You can create files like this format.

**Comment by cploveflower** [comment]
It's very kind of you,I have run the code successfully,
but I set the use_dsst is false,because when I set it's true,
the code has error,I don't know whether the use_dsst is useful？
and I have another question,when it's tracking,if the object is disappearing，
how can I make the bounding box is disappearing too ,Thank you very much

**Comment by tominute** [comment]
1. You may try the version of opencv3.2 or change the related code according to the error.
2. I can't make bb disappearing unless you can detect the object by other methods.
