### ISSUE TITLE
splitting init and tracking

### ISSUE THREAD

**Issue by isgursoy** [tominute/MKCFup#8]
Can you split initialization and update steps?

**Comment by tominute** [comment]
Well, they have been split (e.g. if frame == start_frame, the tracker is initialized, else update).

**Comment by isgursoy** [comment]
Does it mean anything outside frame!=start belongs init? Probably no. Which variables should be kept across updates and inits?
Is not it better to have a class with members and functions instead of spaghetti main?

**Comment by isgursoy** [comment]
I already converted it to the class, but having almost identical init and update stages seems weird. Subwindow extractor also crashes. I can share mine but it is not much different than you told, reference implementation would be cute.

**Comment by tominute** [comment]
I feel very sorry for the long main because of my poor coding ability. Welcome your advanced version sincerely~

**Comment by isgursoy** [comment]
I am not saying your ability is poor, I am saying main is poor.
What are you doing is appreciated and there is room for improvement. Do you want to improve?

**Comment by tominute** [comment]
It's my pleasure if you can share your version but If you ask it for money, i would say sorry.

**Comment by isgursoy** [comment]
Correcting: you are poor, sorry. You should get some help for your psychology.
